export const FUTURES_MARKET_ABI = [
  {
    type: 'function',
    name: 'acceptOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'burn',
    inputs: [
      { name: 'debtToken', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint128', internalType: 'uint128' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'changeExpiration',
    inputs: [
      { name: 'debtToken', type: 'address', internalType: 'address' },
      { name: 'expiration', type: 'uint40', internalType: 'uint40' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'changeLiquidationThreshold',
    inputs: [
      { name: 'debtToken', type: 'address', internalType: 'address' },
      {
        name: 'liquidationThreshold',
        type: 'uint24',
        internalType: 'uint24',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'changeLtv',
    inputs: [
      { name: 'debtToken', type: 'address', internalType: 'address' },
      { name: 'ltv', type: 'uint24', internalType: 'uint24' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'changeMinDebt',
    inputs: [
      { name: 'debtToken', type: 'address', internalType: 'address' },
      { name: 'minDebt', type: 'uint128', internalType: 'uint128' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'close',
    inputs: [
      { name: 'debtToken', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
    ],
    outputs: [
      {
        name: 'collateralReceived',
        type: 'uint128',
        internalType: 'uint128',
      },
    ],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'deposit',
    inputs: [
      { name: 'debtToken', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint128', internalType: 'uint128' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'diamondCut',
    inputs: [
      {
        name: '_diamondCut',
        type: 'tuple[]',
        internalType: 'struct IDiamond.FacetCut[]',
        components: [
          { name: 'facetAddress', type: 'address', internalType: 'address' },
          {
            name: 'action',
            type: 'uint8',
            internalType: 'enum IDiamond.FacetCutAction',
          },
          {
            name: 'functionSelectors',
            type: 'bytes4[]',
            internalType: 'bytes4[]',
          },
        ],
      },
      { name: '_init', type: 'address', internalType: 'address' },
      { name: '_calldata', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'extsload',
    inputs: [{ name: 'slot', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: 'value', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'extsload',
    inputs: [
      { name: 'startSlot', type: 'bytes32', internalType: 'bytes32' },
      { name: 'nSlots', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: 'values', type: 'bytes32[]', internalType: 'bytes32[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'extsload',
    inputs: [{ name: 'slots', type: 'bytes32[]', internalType: 'bytes32[]' }],
    outputs: [{ name: 'values', type: 'bytes32[]', internalType: 'bytes32[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'exttload',
    inputs: [{ name: 'slots', type: 'bytes32[]', internalType: 'bytes32[]' }],
    outputs: [{ name: 'values', type: 'bytes32[]', internalType: 'bytes32[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'exttload',
    inputs: [{ name: 'slot', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: 'value', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'facetAddress',
    inputs: [
      { name: '_functionSelector', type: 'bytes4', internalType: 'bytes4' },
    ],
    outputs: [
      { name: 'facetAddress_', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'facetAddresses',
    inputs: [],
    outputs: [
      {
        name: 'facetAddresses_',
        type: 'address[]',
        internalType: 'address[]',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'facetFunctionSelectors',
    inputs: [{ name: '_facet', type: 'address', internalType: 'address' }],
    outputs: [
      {
        name: 'facetFunctionSelectors_',
        type: 'bytes4[]',
        internalType: 'bytes4[]',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'facets',
    inputs: [],
    outputs: [
      {
        name: 'facets_',
        type: 'tuple[]',
        internalType: 'struct IDiamondLoupe.Facet[]',
        components: [
          { name: 'facetAddress', type: 'address', internalType: 'address' },
          {
            name: 'functionSelectors',
            type: 'bytes4[]',
            internalType: 'bytes4[]',
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getMarket',
    inputs: [{ name: 'debtToken', type: 'address', internalType: 'address' }],
    outputs: [
      {
        name: 'market',
        type: 'tuple',
        internalType: 'struct IMarketView.Market',
        components: [
          { name: 'assetId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'collateral', type: 'address', internalType: 'address' },
          { name: 'expiration', type: 'uint40', internalType: 'uint40' },
          { name: 'ltv', type: 'uint24', internalType: 'uint24' },
          {
            name: 'liquidationThreshold',
            type: 'uint24',
            internalType: 'uint24',
          },
          { name: 'minDebt', type: 'uint128', internalType: 'uint128' },
          { name: 'settlePrice', type: 'uint256', internalType: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPosition',
    inputs: [
      { name: 'debtToken', type: 'address', internalType: 'address' },
      { name: 'user', type: 'address', internalType: 'address' },
    ],
    outputs: [
      { name: 'collateral', type: 'uint128', internalType: 'uint128' },
      { name: 'debt', type: 'uint128', internalType: 'uint128' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isSettled',
    inputs: [{ name: 'debtToken', type: 'address', internalType: 'address' }],
    outputs: [{ name: 'settled', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'liquidate',
    inputs: [
      { name: 'debtToken', type: 'address', internalType: 'address' },
      { name: 'user', type: 'address', internalType: 'address' },
      { name: 'debtToCover', type: 'uint128', internalType: 'uint128' },
      { name: 'skipCallback', type: 'bool', internalType: 'bool' },
      { name: 'data', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [
      { name: 'debtCovered', type: 'uint128', internalType: 'uint128' },
      {
        name: 'collateralLiquidated',
        type: 'uint128',
        internalType: 'uint128',
      },
    ],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'mint',
    inputs: [
      { name: 'debtToken', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint128', internalType: 'uint128' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'multicall',
    inputs: [{ name: 'data', type: 'bytes[]', internalType: 'bytes[]' }],
    outputs: [{ name: 'results', type: 'bytes[]', internalType: 'bytes[]' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'open',
    inputs: [
      { name: 'assetId', type: 'bytes32', internalType: 'bytes32' },
      { name: 'collateral', type: 'address', internalType: 'address' },
      { name: 'expiration', type: 'uint40', internalType: 'uint40' },
      { name: 'ltv', type: 'uint24', internalType: 'uint24' },
      {
        name: 'liquidationThreshold',
        type: 'uint24',
        internalType: 'uint24',
      },
      { name: 'minDebt', type: 'uint128', internalType: 'uint128' },
      { name: 'name', type: 'string', internalType: 'string' },
      { name: 'symbol', type: 'string', internalType: 'string' },
    ],
    outputs: [{ name: 'debtToken', type: 'address', internalType: 'address' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: 'owner_', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingOwner',
    inputs: [],
    outputs: [
      { name: 'pendingOwner_', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'permit',
    inputs: [
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'value', type: 'uint256', internalType: 'uint256' },
      { name: 'deadline', type: 'uint256', internalType: 'uint256' },
      { name: 'v', type: 'uint8', internalType: 'uint8' },
      { name: 'r', type: 'bytes32', internalType: 'bytes32' },
      { name: 's', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'redeem',
    inputs: [
      { name: 'debtToken', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint128', internalType: 'uint128' },
    ],
    outputs: [
      {
        name: 'collateralReceived',
        type: 'uint128',
        internalType: 'uint128',
      },
    ],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'settle',
    inputs: [{ name: 'debtToken', type: 'address', internalType: 'address' }],
    outputs: [
      { name: 'settlePrice', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'supportsInterface',
    inputs: [{ name: 'interfaceID', type: 'bytes4', internalType: 'bytes4' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateOracle',
    inputs: [{ name: 'data', type: 'bytes', internalType: 'bytes' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'withdraw',
    inputs: [
      { name: 'debtToken', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint128', internalType: 'uint128' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'event',
    name: 'Burn',
    inputs: [
      {
        name: 'debtToken',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'burner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      { name: 'to', type: 'address', indexed: true, internalType: 'address' },
      {
        name: 'amount',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChangeExpiration',
    inputs: [
      {
        name: 'debtToken',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'expiration',
        type: 'uint40',
        indexed: false,
        internalType: 'uint40',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChangeLiquidationThreshold',
    inputs: [
      {
        name: 'debtToken',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'liquidationThreshold',
        type: 'uint24',
        indexed: false,
        internalType: 'uint24',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChangeLtv',
    inputs: [
      {
        name: 'debtToken',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      { name: 'ltv', type: 'uint24', indexed: false, internalType: 'uint24' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChangeMinDebt',
    inputs: [
      {
        name: 'debtToken',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'minDebt',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Close',
    inputs: [
      {
        name: 'debtToken',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'closer',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      { name: 'to', type: 'address', indexed: true, internalType: 'address' },
      {
        name: 'amount',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Deposit',
    inputs: [
      {
        name: 'debtToken',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'depositor',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      { name: 'to', type: 'address', indexed: true, internalType: 'address' },
      {
        name: 'amount',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DiamondCut',
    inputs: [
      {
        name: '_diamondCut',
        type: 'tuple[]',
        indexed: false,
        internalType: 'struct IDiamond.FacetCut[]',
        components: [
          { name: 'facetAddress', type: 'address', internalType: 'address' },
          {
            name: 'action',
            type: 'uint8',
            internalType: 'enum IDiamond.FacetCutAction',
          },
          {
            name: 'functionSelectors',
            type: 'bytes4[]',
            internalType: 'bytes4[]',
          },
        ],
      },
      {
        name: '_init',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: '_calldata',
        type: 'bytes',
        indexed: false,
        internalType: 'bytes',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Liquidate',
    inputs: [
      {
        name: 'debtToken',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'liquidator',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'user',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'debtCovered',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
      {
        name: 'collateralLiquidated',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
      {
        name: 'relativePrice',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Mint',
    inputs: [
      {
        name: 'debtToken',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'minter',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      { name: 'to', type: 'address', indexed: true, internalType: 'address' },
      {
        name: 'amount',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
      {
        name: 'relativePrice',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Open',
    inputs: [
      {
        name: 'debtToken',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'assetId',
        type: 'bytes32',
        indexed: false,
        internalType: 'bytes32',
      },
      {
        name: 'collateral',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'expiration',
        type: 'uint40',
        indexed: false,
        internalType: 'uint40',
      },
      { name: 'ltv', type: 'uint24', indexed: false, internalType: 'uint24' },
      {
        name: 'liquidationThreshold',
        type: 'uint24',
        indexed: false,
        internalType: 'uint24',
      },
      {
        name: 'minDebt',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferStarted',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Redeem',
    inputs: [
      {
        name: 'debtToken',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'redeemer',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      { name: 'to', type: 'address', indexed: true, internalType: 'address' },
      {
        name: 'amount',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
      {
        name: 'collateralReceived',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Settle',
    inputs: [
      {
        name: 'debtToken',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'settlePrice',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Withdraw',
    inputs: [
      {
        name: 'debtToken',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'withdrawer',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      { name: 'to', type: 'address', indexed: true, internalType: 'address' },
      {
        name: 'amount',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
    ],
    anonymous: false,
  },
] as const
