name: DeWeb deployer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to DeWeb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build

      - name: Deploy to Massa DeWeb
        id: deploy
        uses: massalabs/deweb-gh-action@v0.0.7
        with:
          config_file: deweb_cli_config.buildnet.json
          source_folder: ./out
        env:
          MASSA_DEWEB_SECRET_KEY: ${{ secrets.MASSA_DEWEB_MAINNET_PKEY }}

      - name: Get deployed website address
        run: |
          echo "Deployed website address: ${{ steps.deploy.outputs.deployed-website }}"